Improved WebSocket messaging in await_deposit.rs and await_invoice.rs
Kodylow/fedimint-http pull request #16
Opened 2024-03-12 19:10 UTC by OsauravO

**This pull request makes the following changes:**
* Fixes issue #13
* I have made changes in handle_socket function  and accordingly in match_method in ws.rs file to improve the websocket messaging logic

2024-03-12 19:10 UTC, OsauravO commented
@Kodylow  i have made some changes in handle_socket function  and accordingly in match_method in ws.rs file and also tried to explain my approach using comments . Accordingly i have changed handle_ws function in await_deposit.rs file . I am still getting some errors . Can you please check it for me . thanks

2024-03-12 19:56 UTC, Kodylow requested changes

2024-03-12 19:56 UTC, Kodylow commented on src/router/handlers/fedimint/ln/await_invoice.rs
> +        ws_sender.send(Message::Text(message)).await.map_err(|_| AppError::from(StatusCode::INTERNAL_SERVER_ERROR))?;
this is looking like the right direction but the request needs to be correlated to the response by the id, don't think that's being added in here. Also this is just putting text it should probably be json structured or use enums for the responses so they can be deterministically consumed by the client

2024-03-12 19:56 UTC, Kodylow commented on src/router/handlers/fedimint/ln/await_invoice.rs
> +// }
all the functionaliy needs to be able to handle both rest and websockets, you need to abstract it as such

2024-03-12 19:56 UTC, Kodylow commented on src/router/handlers/fedimint/wallet/await_deposit.rs
> +            ws_sender.send(Message::Text(message)).await.map_err(|_| AppError::from(StatusCode::INTERNAL_SERVER_ERROR))?;
again, enums and json structs > text messages. See how I structured the json responses for websockets previosuly, think it's in `ws.rs` under build response

2024-03-15 18:02 UTC, OsauravO commented
@Kodylow i tried to resolve all the changes you suggested but i am getting an error in ws.rs file . Can you please check it for me. Thanks

2024-03-15 19:29 UTC, Kodylow commented
can you rebase + post the errors

2024-03-16 06:03 UTC, OsauravO commented
i think i have done the rebasing now. 
and the error which i am getting in ws.rs file is
![image](https://github.com/Kodylow/fedimint-http/assets/123803605/e077d65e-6660-4058-b1dd-710298bb945f)

2024-03-16 18:09 UTC, Kodylow commented
Okay, that error's pretty clear, you're passing ownership of the socket into the method which drops it so you have to either borrow it like `&socket`, clone it like `socket.clone()`, or refactor to not drop the socket

2024-03-16 19:17 UTC, OsauravO commented
hey i think i got what you said , can you now check it . Thanks a lot

2024-03-20 01:24 UTC, Kodylow commented
Can you reopen this on https://github.com/fedimint/fedimint-clientd , moved the project into the fedimint org

2024-03-20 03:30 UTC, OsauravO commented
Already done 👍

2024-03-22 17:15 UTC, Kodylow commented
closing with move to new repo

2024-03-22 17:15 UTC, closed without merging